services:
  - type: web
    name: intellimen-website
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: intellimen-db
          property: connectionString

databases:
  - name: intellimen-db
    databaseName: intellimen
    user: intellimen_user